# Site settings
title: Abdul's Blog
description: Blog to share my updates
baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Abdul Rehman
user_description: A Cloud Solution Architect & Python/Django Developer
user_title: Cloud Solution Architect & Python/Django Developer
email: aycloud7@icloud.com
twitter_username: N_innovator
github_username:  arycloud
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
