# Site settings
title: Abdul's Blog
description: Blog to share my updates
baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Abdul Rehman
user_description: I'm Abdul Rehman,a Cloud Solution Architect & Python/Django Developer.My aim is to work in a challenging work environment and utilize my technical expertise to make this world the best place.I'm Working on web development from 5 years.Done more than 50 projects on Google Cloud Platform.
user_title: Cloud Solution Architect & Python/Django Developer
email: aycloud7@icloud.com
twitter_username: N_innovator
github_username:  arycloud
linkedin_username:  ninnovator

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
